# -----------------------------------------------------
#  Copyright Iliass Mahjoub 2022.                     
#  Distributed under the Boost Software License,      
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)   
# -----------------------------------------------------

name: hash_sha256_codacy_coverage_reporter

on: ["push"]

jobs:
  hash_sha256-codacy-coverage-reporter:
    runs-on: ubuntu-22.04
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
      - name: gnumake-gcc-gcov-native
        run: |
          echo "build and run gcov/lcov/genhtml"
          g++ -x c++ -c -mtune=native -march=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=c++17 -fno-inline-functions -fprofile-arcs -ftest-coverage hash_sha256.cpp -I. -o hash_sha256.o
          g++ -mtune=native -march=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=c++17 -fno-inline-functions -fprofile-arcs -ftest-coverage hash_sha256.o -o hash_sha256.exe
          ./hash_sha256.exe
          gcov --object-directory . --demangled-names ./hash_sha256.cpp
          lcov -c --directory . --output-file coverage_unfiltered.info
          lcov --remove coverage_unfiltered.info '/usr/*' --output-file coverage.info
      - name: upload-codecov
        uses: codecov/codecov-action@v2
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          files: coverage.info
