name: hash_sha256_codecov
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  gcc-clang-native:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        standard: [ c++14 ]
        compiler: [ g++ ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install lcov
      - name: gnumake-gcc-gcov-native
        run: |
          echo "build and run gcov/lcov/genhtml"
          ${{ matrix.compiler }} -x none -mtune=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=${{ matrix.standard }} -ftest-coverage hash_sha256_test.cpp -I. -o hash_sha256_test.exe
          echo +++ execute hash_sha256_test.exe
          ./hash_sha256_test.exe
          echo
          echo +++ running gcov
          gcov $(GCOV_FLAGS) $(addsuffix .cpp,$(FILES_PRJ))
          echo
          echo +++ running lcov
          lcov --rc lcov_branch_coverage=1 -c --directory obj --output-file coverage_unfiltered.info
          lcov --rc lcov_branch_coverage=1 --remove coverage_unfiltered.info --output-file coverage.info
          echo
          echo +++ running genhtml
          genhtml coverage.info --rc lcov_branch_coverage=1 --demangle-cpp --output-directory ./report
          echo

      - name: upload-codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          functionalities: fix
