name: hash_sha256_codecov
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  gcc-clang-native:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        standard: [ c++17 ]
        compiler: [ g++ ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install lcov
      - name: gnumake-gcc-gcov-native
        run: |
          echo "build and run gcov/lcov/genhtml"
          g++ -x c++ -c -mtune=native -march=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=c++17 -fno-inline-functions -fprofile-arcs -ftest-coverage hash_sha256_test.cpp -I. -o hash_sha256_test.o
          g++ -mtune=native -march=native -O2 -Wall -Wextra -Wconversion -Wsign-conversion -std=c++17 -fno-inline-functions -fprofile-arcs -ftest-coverage hash_sha256_test.o -o hash_sha256_test.exe
          ./hash_sha256_test.exe
          gcov --object-directory . --demangled-names ./hash_sha256_test.cpp
          lcov -c --directory . --output-file coverage_unfiltered.info
          lcov --remove coverage_unfiltered.info '/usr/*' --output-file coverage.xml
      - name: upload-codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
          functionalities: fix
